### ISSUE TITLE
AjaxCrudjTablePaginationSample: You can update your code to use Spring JDBC

### ISSUE THREAD

**Issue by JavaNeed** [priyadb/AjaxCrudjTablePaginationSample#3]
I think this is an old fashionable coding practises doesn't works in 2016. I will be trying to convert it into the Spring JDBC. If able to do that today, will share the link for reference.

**Comment by priyadb** [comment]
Sorry about the class files. I removed everything except source and web content. This project is explained in a series of tutorials on how to use jTable in Java applications - http://www.programming-free.com/2014/02/jtable-pagination-in-java-web.html
